# Generated by Django 4.1 on 2024-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_proxyemployee1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyEmployee2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.employee',),
        ),
    ]
